[build]
  # Build command - sadece frontend build
  command = "npm run build"
  # Frontend dosyalarının konumu
  publish = "dist/public"
  # Functions klasörü
  functions = "netlify/functions"

[build.environment]
  # Node version
  NODE_VERSION = "20"

# API route'larını Netlify Functions'a yönlendir
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA routing için fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  # Functions ayarları
  node_bundler = "esbuild"
  
[dev]
  # Local development
  command = "npm run dev"
  port = 5000